name: BlockReference
version: 1.2
main: bonn2.BlockReference.Main
api-version: 1.13
authors: [bonn2]
description: Gets reletive coordinants for use in commands
website: discord.gg/TQk388w
commands:
  blockreference:
    description: Main BlockReference Command
    aliases: blr
    permission: blockreference.user
    permission-message: You not have have permission to use this command!
    usage: /blockreference <toggle | look | clear>
